---
- name: Primer paso
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/variables.yml
  vars:
    var_1: Ivan
    archivos_a_enviar:
      - .vimrc
      - .bash_history
      - .tmux.conf

  tasks:
    # - name: Imprimir mensaje texto
    #   ansible.builtin.debug:
    #     msg: "Hola {{ Var_1 }} - {{ ansible_hostname }}"

    - name: Buscar archivos locales
      ansible.builtin.find:
        path: "{{ playbook_dir }}/files"
        hidden: true
      delegate_to: localhost
      connection: local
      run_once: true
      register: archivos_a_enviar
      tags:
        - buscar_archivos

    - name: Mostrar archivos
      ansible.builtin.debug:
        msg: "{{ archivos_a_enviar }}"
      tags:
        - buscar_archivos

    - name: Copy config files
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: /home/dm0n/
      loop: "{{ archivos_a_enviar.files }}"

    - name: Mostrar variables
      ansible.builtin.debug:
        msg: "{{ var_string }}"
      tags:
        - variables

    - name: Mostrar variables
      ansible.builtin.debug:
        msg: "{{ var_boolean_may }}"
      tags:
        - variables

    - name: Mostrar variables
      ansible.builtin.debug:
        msg: "{{ var_lista_1[1] }}"
      tags:
        - variables

    - name: Mostrar variables
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ var_lista_1 }}"
      tags:
        - variables

    - name: Mostrar variables
      ansible.builtin.debug:
        msg: "{{ var_diccionario['llave2'] }}"
      tags:
        - variables

    - name: Mostrar variables
      ansible.builtin.debug:
        msg: "{{ var_diccionario.llave3 }}"
      tags:
        - variables

    - name: Mostrar variables
      ansible.builtin.debug:
        msg: "{{ lista_diccionarios[0].nombre }}"
      tags:
        - variables

    - name: Lectura de archivo bash history
      ansible.builtin.slurp:
        src: "{{ playbook_dir }}/files/.bash_history"
      register: contenido_archivo
      delegate_to: localhost
      connection: local
      run_once: true
      tags: 
        - slurp

    - name: Print returned information
      ansible.builtin.debug:
        var: "contenido_archivo"
      tags: 
        - slurp

    - name: Print returned information
      ansible.builtin.debug:
        msg: "{{ contenido_archivo['content'] | b64decode }}"

    - name: Imprimir tarea
      ansible.builtin.debug:
        msg: "Imprime mensaje"
      tags: 
        - slurp
      when: 
        - 'not "steam" in (contenido_archivo.content | b64decode)'
        - '"tmux" in (contenido_archivo.content | b64decode)'
      # when: (contenido_archivo.content | b64decode).find("steam") == -1
    
